from django.shortcuts import render

from rest_framework.decorators import api_view
from rest_framework.decorators import parser_classes
from rest_framework.response import Response
from rest_framework.parsers import FormParser
from rest_framework.parsers import MultiPartParser
from rest_framework.parsers import JSONParser
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import permission_classes
from rest_framework.decorators import renderer_classes
from rest_framework.permissions import AllowAny
from rest_framework import status
from rest_framework.pagination import PageNumberPagination

import random



@api_view(['GET'])
@permission_classes((AllowAny,))
#@renderer_classes((JSONRenderer,))
def confucius(request):
  thoughts = ['He who will not economize will have to agonize.',
              'Our greatest glory is not in never falling, but in getting up every time we do.',
              'They must often change who would be constant in happiness or wisdom.',
              'To go beyond is as wrong as to fall short.',
              'The people may be made to follow a path of action, but they may not be made to understand it.',
              'The superior man is modest in his speech, but exceeds in his actions.',
              'He with whom neither slander that gradually soaks into the mind, nor statements that startle like a wound in the flesh, are successful may be called intelligent indeed.',
              'If a man takes no thought about what is distant, he will find sorrow near at hand.',
              'It does not matter how slowly you go as long as you do not stop.',
              'Everything has its beauty, but not everyone sees it.',
              'I hear and I forget. I see and I remember. I do and I understand.',
              'Life is really simple, but we insist on making it complicated.',
              'Before you embark on a journey of revenge, dig two graves.',
              "Men's natures are alike, it is their habits that carry them far apart."]
  return Response(random.choice(thoughts))


@api_view(['GET'])
@permission_classes((AllowAny,))
def bs(request):
  adverbs = [
    'appropriately',
    'assertively',
    'authoritatively',
    'collaboratively',
    'compellingly',
    'competently',
    'completely',
    'continually',
    'conveniently',
    'credibly',
    'distinctively',
    'dramatically',
    'dynamically',
    'efficiently',
    'energistically',
    'enthusiastically',
    'fungibly',
    'globally',
    'holisticly',
    'interactively',
    'intrinsically',
    'monotonectally',
    'objectively',
    'phosfluorescently',
    'proactively',
    'professionally',
    'progressively',
    'quickly',
    'rapidiously',
    'seamlessly',
    'synergistically',
    'uniquely']

  verbs = [
    'actualize',
    'administrate',
    'aggregate',
    'architect',
    'benchmark',
    'brand',
    'build',
    'cloudify',
    'communicate',
    'conceptualize',
    'coordinate',
    'create',
    'cultivate',
    'customize',
    'deliver',
    'deploy',
    'develop',
    'dinintermediate disseminate',
    'drive',
    'effectivize',
    'embrace',
    'e-enable',
    'empower',
    'enable',
    'engage',
    'engineer',
    'enhance',
    'envisioneer',
    'evisculate',
    'evolve',
    'expedite',
    'exploit',
    'extend',
    'fabricate',
    'facilitate',
    'fashion',
    'formulate',
    'foster',
    'generate',
    'grow',
    'harness',
    'impact',
    'implement',
    'incentivize',
    'incubate',
    'initiate',
    'innovate',
    'integrate',
    'iterate',
    'leverage existing',
    "leverage other's",
    'maintain',
    'matrix',
    'maximize',
    'mesh',
    'monetize',
    'morph',
    'myocardinate',
    'negotiate',
    'network',
    'optimize',
    'orchestrate',
    'parallel task',
    'pivot',
    'plagiarize',
    'pontificate',
    'predominate',
    'procrastinate',
    'productivate',
    'productize',
    'promote',
    'provide access to',
    'pursue',
    'recaptiualize',
    'reconceptualize',
    'redefine',
    're-engineer',
    'reintermediate',
    'reinvent',
    'repurpose',
    'restore',
    'revolutionize',
    'right-shore',
    'scale',
    'seize',
    'simplify',
    'strategize',
    'streamline',
    'supply',
    'syndicate',
    'synergize',
    'synthesize',
    'target',
    'transform',
    'transition',
    'triage',
    'underwhelm',
    'unleash',
    'utilize',
    'visualize',
    'whiteboard']

  adjectives = [
    '24/7',
    '24/365',
    'accurate',
    'adaptive',
    'alternative',
    'an expanded array of',
    'B2B',
    'B2C',
    'backend',
    'backward-compatible',
    'best-of-breed',
    'bleeding-edge',
    'bricks-and-clicks',
    'business',
    'clicks-and-mortar',
    'client-based',
    'client-centered',
    'client-centric',
    'client-focused',
    'cloud-based',
    'cloud-centric',
    'cloudified',
    'collaborative',
    'compelling',
    'competitive',
    'cooperative',
    'corporate',
    'cost effective',
    'covalent',
    'cross functional',
    'cross-media',
    'cross-platform',
    'cross-unit',
    'customer directed',
    'customized',
    'cutting-edge',
    'distinctive',
    'distributed',
    'diverse',
    'dynamic',
    'e-business',
    'economically sound',
    'effective',
    'efficient',
    'elastic',
    'emerging',
    'empowered',
    'enabled',
    'end-to-end',
    'enterprise',
    'enterprise-wide',
    'equity invested',
    'error-free',
    'ethical',
    'excellent',
    'exceptional',
    'extensible',
    'extensive',
    'flexible',
    'focused',
    'frictionless',
    'front-end',
    'fully researched',
    'fully tested',
    'functional',
    'functionalized',
    'fungible',
    'future-proof',
    'global',
    'go forward',
    'goal-oriented',
    'granular',
    'high standards in',
    'high-payoff',
    'hyperscale',
    'high-quality',
    'highly efficient',
    'holistic',
    'impactful',
    'inexpensive',
    'innovative',
    'installed base',
    'integrated',
    'interactive',
    'interdependent',
    'intermandated',
    'interoperable',
    'intuitive',
    'just in time',
    'leading-edge',
    'leveraged',
    'long-term high-impact',
    'low-risk high-yield',
    'magnetic',
    'maintainable',
    'market positioning',
    'market-driven',
    'mission-critical',
    'multidisciplinary',
    'multifunctional',
    'multimedia based',
    'next-generation',
    'on-demand',
    'one-to-one',
    'open-source',
    'optimal',
    'orthogonal',
    'out-of-the-box',
    'pandemic',
    'parallel',
    'performance based',
    'plug-and-play',
    'premier',
    'premium',
    'principle-centered',
    'proactive',
    'process-centric',
    'professional',
    'progressive',
    'prospective',
    'quality',
    'real-time',
    'reliable',
    'resource-sucking',
    'resource-maximizing',
    'resource-leveling',
    'revolutionary',
    'robust',
    'scalable',
    'seamless',
    "silo'ed",
    'stand-alone',
    'standardized',
    'standards compliant',
    'state of the art',
    'sticky',
    'strategic',
    'superior',
    'sustainable',
    'synergistic',
    'tactical',
    'team building',
    'team driven',
    'technically sound',
    'timely',
    'top-line',
    'transparent',
    'turnkey',
    'ubiquitous',
    'unique',
    'user-centric',
    'user friendly',
    'value-added',
    'vertical',
    'viral',
    'virtual',
    'visionary',
    'web-enabled',
    'wireless',
    'world-class',
    'worldwide']

  nouns = [
    'action items',
    'alignments',
    'applications',
    'architectures',
    'bandwidth',
    'benefits',
    'best practices',
    'catalysts for change',
    'channels',
    'clouds',
    'collaboration and idea-sharing',
    'communities',
    'content',
    'convergence',
    'core competencies',
    'customer service',
    'data',
    'deliverables',
    'e-business',
    'e-commerce',
    'e-markets',
    'e-tailers',
    'e-services',
    'experiences',
    'expertise',
    'functionalities',
    'fungibility',
    'growth strategies',
    'human capital',
    'ideas',
    'imperatives',
    'infomediaries',
    'information',
    'infrastructures',
    'initiatives',
    'innovation',
    'intellectual capital',
    'interfaces',
    'internal or "organic" sources',
    'leadership',
    'leadership skills',
    'manufactured products',
    'markets',
    'materials',
    'meta-services',
    'methodologies',
    'methods of empowerment',
    'metrics',
    'micro-moments'
    'mindshare',
    'models',
    'networks',
    'niches',
    'niche markets',
    'nosql',
    'opportunities',
    '"outside the box" thinking',
    'outsourcing',
    'paradigms',
    'partnerships',
    'platforms',
    'portals',
    'potentialities',
    'process improvements',
    'processes',
    'products',
    'quality vectors',
    'relationships',
    'resources',
    'results',
    'ROI',
    'scenarios',
    'schemas',
    'services',
    'solutions',
    'sources',
    'strategic theme areas',
    'storage',
    'supply chains',
    'synergy',
    'systems',
    'technologies',
    'technology',
    'testing procedures',
    'total linkage',
    'users',
    'value',
    'vortals',
    'web-readiness',
    'web services',
    'virtualization']

  start = ['You should', 'We need to', "Let's"]
  return Response("{0} {1} {2} {3} {4}.".format(random.choice(start), random.choice(adverbs),
                                         random.choice(verbs), random.choice(adjectives),
                                         random.choice(nouns)))
